apiVersion: v1
kind: Pod
metadata:
  name: sonarscanner
  labels:
    app: sonarscanner
spec:
  containers:
  - name: sonarscanner
    image: sonarsource/sonar-scanner-cli:latest
    command: [ "sleep", "infinity" ]